#!/bin/sh -efux

yrepo=http://ftp.altlinux.org/pub/distributions/archive/sisyphus/date/2018

DL()
{
    [ -s "$2" ] || wget -O "$2" "$1"
}

mkdir -p data

for mon in `seq 1 12`; do
    mon=`printf %02d $mon`
    repo=$yrepo/$mon/01
    for arch in x86_64 noarch; do
	DL {$repo/$arch/base/,data/$mon-$arch-}srclist.classic.xz
	DL {$repo/$arch/base/,data/$mon-$arch-}pkglist.classic.xz
	qsrc='%{Name}-%{Version}-%{Release}.src.rpm\n'
	qpkg='%{Name}-%{Version}-%{Release}.%{Arch}.rpm\t%{SourceRPM}\n'
	xz -d <data/$mon-$arch-srclist.classic.xz |pkglist-query "$qsrc" - >data/$mon-$arch-src.list
	xz -d <data/$mon-$arch-pkglist.classic.xz |pkglist-query "$qpkg" - >data/$mon-$arch-pkg.list
    done
done
