#!/bin/sh -efu
[ -s zstd/lib/libzstd.a ] ||
make -C zstd/lib libzstd.a-mt
gcc -g -O2 -Wall -D_GNU_SOURCE train-srclist.c -lt1ha -o train-srclist \
    -Izstd/lib/dictBuilder -pthread zstd/lib/libzstd.a
# The dictionary should be train on the old state.
xz -d <OLD-srclist.classic.xz |./train-srclist
